# Generated by Django 6.0.2 on 2026-02-21 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('builder', 'Builder'), ('upload', 'Upload')], default='builder', max_length=10)),
                ('project_model_url', models.URLField(blank=True, default='')),
                ('steps', models.JSONField(default=list)),
                ('connections', models.JSONField(default=list)),
                ('guide', models.JSONField(default=list)),
                ('node_positions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
