# Generated by Django 6.0.2 on 2026-02-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_model_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
