# Generated by Django 5.2.9 on 2026-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_created3dmodelm_uploaded3dmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='created3dmodelm',
            name='texture_data_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
