# Generated by Django 5.2.9 on 2026-03-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='created3dmodelm',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='uploaded3dmodel',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
