# Generated by Django 5.2.9 on 2026-03-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_created3dmodelm_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded3dmodel',
            name='system_model',
            field=models.BooleanField(default=False),
        ),
    ]
